apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: cert-manager
  name: letsencrypt-prod
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "infradev@oldcowboyshop.com"
    privateKeySecretRef:
      name: "letsencrypt-prod"
    solvers:
    - http01:
        ingress:
          class: nginx
    - dns01:
        route53:
          region: "us-east-1"
          hostedZoneID: "Z0429761CE12TWM5FTR2"




